### ISSUE TITLE
Workshop Drilling++

### ISSUE THREAD

**Issue by prusse-martin** [ESSS/talks#32]
12/12 o Fabio vai fazer um workshop para o time do PWDa. 
**Como vivem? O que comem? O que fazem?**
Essas e muitas outras perguntas serão respondidas nesse workshop onde vamos aprender com o nosso super time de produto tudo sobre o PWDa.
Curvas, funcionalidades, diagnósticos, tudo isso e muito mais! 
Não perca essa oportunidade!

**Comment by rafaeljalves** [comment]
Parte 1 -> https://drive.google.com/drive/u/0/folders/1F7KMBPJI_ToDszeA0lCU9ZHHnCk0_RST
Parte 2 -> https://drive.google.com/open?id=1RPcHSnaN3eWx9bnOZWqbFTs6tKqsIZYO&usp=chrome_ntp
